<?php
declare(strict_types=1);
namespace CaveTrip\Controllers;
use CaveTrip\Core\Application; use CaveTrip\Core\Http; use CaveTrip\Core\Session; use CaveTrip\Core\View;
use CaveTrip\Services\CaveService; use CaveTrip\Services\TripParticipantService; use CaveTrip\Services\TripReportService; use CaveTrip\Services\TripService;
final class TripReportController extends BaseController
{
    public function index(Application $app):string { $u=$this->requireMember($app);$g=$this->grottoId($u);$f=['q'=>$_GET['q']??'','cave_id'=>$_GET['cave_id']??'','from'=>$_GET['from']??'','to'=>$_GET['to']??''];return View::render($app,'trip-reports/index',['title'=>'Trip Reports','currentUser'=>$u,'reports'=>(new TripReportService($app->db()))->search($g,$f),'caves'=>(new CaveService($app->db()))->listForGrotto($g),'filters'=>$f]); }
    public function show(Application $app):string { $u=$this->requireLogin($app);$g=$this->grottoId($u);$r=(new TripReportService($app->db()))->findForGrotto((int)($_GET['id']??0),$g);if(!$r){http_response_code(404);return View::render($app,'pages/404',['title'=>'Trip Report Not Found']);}$trip=(new TripService($app->db()))->findForGrotto((int)$r['trip_id'],$g);if(!$trip||!$this->canReport($app,$u,$trip)){http_response_code(403);return 'Forbidden';}return View::render($app,'trip-reports/show',['title'=>'Trip Report','currentUser'=>$u,'report'=>$r,'canEdit'=>$this->canEdit($u,$r)]); }
    public function create(Application $app):string { $u=$this->requireLogin($app);$g=$this->grottoId($u);$trip=(new TripService($app->db()))->findForGrotto((int)($_GET['trip_id']??0),$g);if(!$trip){http_response_code(404);return View::render($app,'pages/404',['title'=>'Trip Not Found']);}if((string)$trip['status']!=='completed'||!$this->canReport($app,$u,$trip)){http_response_code(403);return 'Trip reports are available to trip participants after the trip is completed.';}return View::render($app,'trip-reports/form',['title'=>'Submit Trip Report','currentUser'=>$u,'trip'=>$trip,'report'=>null,'action'=>'/trip-reports?trip_id='.(int)$trip['id'],'participantNames'=>$this->participantNames($app,(int)$trip['id'])]); }
    public function store(Application $app):string { Http::requirePostCsrf();$u=$this->requireLogin($app);$g=$this->grottoId($u);$trip=(new TripService($app->db()))->findForGrotto((int)($_GET['trip_id']??0),$g);if(!$trip||(string)$trip['status']!=='completed'||!$this->canReport($app,$u,$trip)){http_response_code(403);return 'Forbidden';}try{$id=(new TripReportService($app->db()))->create($g,$trip,$this->userId($u),$this->participantNames($app,(int)$trip['id']),$_POST);$this->audit($app)->tripReportCreated($g,$this->userId($u),$id,(int)$trip['id']);Session::flash('success','Trip report submitted. Additional participants may submit their own reports.');return Http::redirect('/trip-reports/show?id='.$id);}catch(\Throwable $e){Session::flash('error','Unable to submit report: '.$e->getMessage());return Http::redirect('/trip-reports/create?trip_id='.(int)$trip['id']);} }
    public function edit(Application $app):string { $u=$this->requireLogin($app);$g=$this->grottoId($u);$r=(new TripReportService($app->db()))->findForGrotto((int)($_GET['id']??0),$g);if(!$r){http_response_code(404);return View::render($app,'pages/404',['title'=>'Trip Report Not Found']);}if(!$this->canEdit($u,$r)){http_response_code(403);return 'Forbidden';}$trip=(new TripService($app->db()))->findForGrotto((int)$r['trip_id'],$g);return View::render($app,'trip-reports/form',['title'=>'Edit Trip Report','currentUser'=>$u,'trip'=>$trip,'report'=>$r,'action'=>'/trip-reports/update?id='.(int)$r['id'],'participantNames'=>$this->decodeNames((string)$r['participant_names_json'])]); }
    public function update(Application $app):string { Http::requirePostCsrf();$u=$this->requireLogin($app);$g=$this->grottoId($u);$id=(int)($_GET['id']??0);$s=new TripReportService($app->db());$r=$s->findForGrotto($id,$g);if(!$r||!$this->canEdit($u,$r)){http_response_code(403);return 'Forbidden';}try{$s->update($id,$g,$_POST);$this->audit($app)->tripReportUpdated($g,$this->userId($u),$id,(int)$r['trip_id']);Session::flash('success','Trip report updated.');return Http::redirect('/trip-reports/show?id='.$id);}catch(\Throwable $e){Session::flash('error','Unable to update report: '.$e->getMessage());return Http::redirect('/trip-reports/edit?id='.$id);} }
    private function canReport(Application $app,array $u,array $trip):bool { if(in_array((string)$u['role'],['super_admin','admin'],true)||(int)$trip['trip_leader_user_id']===$this->userId($u))return true;return(new TripParticipantService($app->db()))->isUserOnTrip((int)$trip['id'],$this->userId($u)); }
    private function canEdit(array $u,array $r):bool { return in_array((string)$u['role'],['super_admin','admin'],true)||(int)$r['author_user_id']===$this->userId($u); }
    private function participantNames(Application $app,int $tripId):array { $rows=(new TripParticipantService($app->db()))->listForTrip($tripId);$names=[];foreach($rows as $row){if(in_array((string)($row['participant_status']??''),['removed','cancelled','waitlisted'],true))continue;$n=trim((string)($row['name']??$row['email']??''));if($n!==''&&!in_array($n,$names,true))$names[]=$n;}return$names; }
    private function decodeNames(string $json):array { $v=json_decode($json,true);return is_array($v)?array_values(array_filter(array_map('strval',$v))):[]; }
}
